version: '3'
services:
  db-mysql:
    image: "mysql:8.0"
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=critter
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    volumes:
    - critter_data:/var/lib/mysql
  app:
    image: "spring-boot-app"
    restart: on-failure
    depends_on:
      - db-mysql
    command: ["/home/critter/wait-for-it.sh", "db-mysql:3306", "--", "java", "-jar", "/home/critter/target/critter-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080"
    build:
      context: "./"
      dockerfile: "Dockerfile"
  nginx:
    image: nginx
    restart: always
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  critter_data:
